
image: python:latest

tasks:
  - before: |
      printf 'export PATH="%s:$PATH"\n' "~/.local/bin" >> $HOME/.bashrc && exit
  - init: |
      pip install pycodestyle

vscode:
  extensions:
    - ms-python.python